# Generated by Django 4.2.3 on 2023-07-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50)),
                ('recipe_des', models.TextField()),
                ('recipe_image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
