# Generated by Django 4.2.3 on 2023-07-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
