# Generated by Django 4.2.3 on 2023-07-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_rename_recipes_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
