# Generated by Django 4.2.3 on 2023-07-24 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_register_page_login_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_page',
        ),
    ]
