# Generated by Django 4.2.3 on 2023-07-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_delete_login_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_page',
            name='user',
        ),
    ]
