# Generated by Django 4.2.3 on 2023-07-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_registerpage_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterPage',
        ),
    ]
