# Generated by Django 4.2.3 on 2023-07-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
