# Generated by Django 4.2.3 on 2023-07-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_count',
            field=models.IntegerField(default=1),
        ),
    ]
