# Generated by Django 4.2.3 on 2023-07-26 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0018_department_studentid_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Student_email',
            new_name='student_email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sutdent_name',
            new_name='student_name',
        ),
    ]
