# Generated by Django 4.2.3 on 2023-07-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0019_rename_student_email_student_student_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department']},
        ),
    ]
