# Generated by Django 4.2.3 on 2023-07-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0020_alter_department_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_name']},
        ),
    ]
