# Generated by Django 4.2.3 on 2023-07-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0021_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentid',
            options={'ordering': ['student_id']},
        ),
    ]
