# Generated by Django 5.1.4 on 2025-01-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0026_remove_student_department_remove_student_student_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=models.ImageField(null=True, upload_to="static"),
        ),
    ]
